# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  push:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Test script
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x generate-module-skeleton.sh
          printf "$GITHUB_WORKSPACE/test\ntest-module\ny\n" | ./generate-module-skeleton.sh

